export const demoProducts = [
  {
    id: 0,
    title: 'Personalized Floral Wedding Invitation Printable Card',
    description: 'Beautiful personalized wedding invitation with floral design.',
    price: 5.99,
    tags: ['wedding', 'invitation', 'printable', 'personalized', 'floral', 'card', 'digital'],
    image_name: 'demo1.jpg',
    quantity: 999,
    approved: false,
    variations: [],
    variationCombinations: {},
  },
  {
    id: 1,
    title: 'Minimalist Birthday Card Instant Download PNG Template',
    description: 'Clean minimalist birthday card template, instant download.',
    price: 3.49,
    tags: ['birthday', 'card', 'minimalist', 'instant download', 'printable', 'template'],
    image_name: 'demo2.jpg',
    quantity: 999,
    approved: false,
    variations: [],
    variationCombinations: {},
  },
  {
    id: 2,
    title: 'Boho Baby Shower Invitation Editable Canva Template',
    description: 'Editable boho style baby shower invitation for Canva.',
    price: 4.99,
    tags: ['baby shower', 'boho', 'invitation', 'editable', 'canva', 'template', 'printable'],
    image_name: 'demo3.jpg',
    quantity: 999,
    approved: false,
    variations: [],
    variationCombinations: {},
  },
  {
    id: 3,
    title: 'Modern Resume Template Word Google Docs Instant Download',
    description: 'Professional modern resume template for Word and Google Docs.',
    price: 8.99,
    tags: ['resume', 'template', 'modern', 'word', 'google docs', 'professional', 'cv', 'instant download'],
    image_name: 'demo4.jpg',
    quantity: 999,
    approved: false,
    variations: [],
    variationCombinations: {},
  },
]
